# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 16:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('csv_file', models.FileField(upload_to='file_data')),
                ('history_line', models.CharField(blank=True, default=0, max_length=50)),
                ('finish_input_data', models.BooleanField(default=False)),
                ('match_option', models.CharField(choices=[('LEAVE_UNMATCHED', 'Leave unmatched for manual matching later'), ('AUTO_UNMATCHED', 'Automatically attempt to match via online services')], default='AUTO_UNMATCHED', help_text='(required) Note: online services may return vague matches (e.g., "US" with lat/long in the middle of the country).', max_length=30, verbose_name="For addresses unmatched in ProvPlan's database:")),
                ('match_score', models.DecimalField(blank=True, decimal_places=2, default=85, help_text='use online services geo_score will be blank', max_digits=11, null=True, verbose_name="For addresses geo_score lower then this score in ProvPlan's database:")),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
