# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-17 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocode', '0002_auto_20160217_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('key', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
