# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-17 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geocode', '0003_apikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKeyAcceptValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('value', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='apikey',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apikeyacceptvalue',
            name='api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geocode.ApiKey'),
        ),
    ]
