# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-17 18:08
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geocode', '0004_auto_20160217_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_id', models.CharField(blank=True, max_length=256)),
                ('street', models.CharField(blank=True, max_length=80)),
                ('ignore_street', models.BooleanField(default=False)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('ignore_city', models.BooleanField(default=False)),
                ('state', models.CharField(blank=True, max_length=80)),
                ('ignore_state', models.BooleanField(default=False)),
                ('zip', models.CharField(blank=True, max_length=80)),
                ('geo_score', models.DecimalField(blank=True, decimal_places=2, help_text="Online Resource (GoogleV3, Bing, MapQuest) and User Edit own't have Geo score", max_digits=11, null=True)),
                ('geo_address', models.CharField(blank=True, max_length=180)),
                ('geo_lat', models.CharField(blank=True, help_text='projection 4326', max_length=80)),
                ('geo_lon', models.CharField(blank=True, help_text='projection 4326', max_length=80)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('have_value', models.BooleanField(default=False)),
                ('flag', models.BooleanField(default=False)),
                ('resource', models.CharField(blank=True, default='', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='RecordAddressIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_row_id', models.CharField(blank=True, max_length=180)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geocode.Address')),
            ],
        ),
        migrations.RenameField(
            model_name='record',
            old_name='address_id',
            new_name='user_defind_id',
        ),
        migrations.RemoveField(
            model_name='record',
            name='city',
        ),
        migrations.RemoveField(
            model_name='record',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='record',
            name='flag',
        ),
        migrations.RemoveField(
            model_name='record',
            name='geo_address',
        ),
        migrations.RemoveField(
            model_name='record',
            name='geo_lat',
        ),
        migrations.RemoveField(
            model_name='record',
            name='geo_lon',
        ),
        migrations.RemoveField(
            model_name='record',
            name='geo_score',
        ),
        migrations.RemoveField(
            model_name='record',
            name='have_value',
        ),
        migrations.RemoveField(
            model_name='record',
            name='ignore_city',
        ),
        migrations.RemoveField(
            model_name='record',
            name='ignore_state',
        ),
        migrations.RemoveField(
            model_name='record',
            name='ignore_street',
        ),
        migrations.RemoveField(
            model_name='record',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='record',
            name='state',
        ),
        migrations.RemoveField(
            model_name='record',
            name='street',
        ),
        migrations.RemoveField(
            model_name='record',
            name='zip',
        ),
        migrations.AlterField(
            model_name='projectfield',
            name='match_option',
            field=models.CharField(blank=True, choices=[('ADDRESS_ID', 'AddressID'), ('STREET', 'Street'), ('CITY', 'City'), ('STATE', 'State'), ('ZIP', 'Zip')], help_text='(required) Select AddressID, Street, City, State, Zip', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='recordaddressindex',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geocode.Record'),
        ),
        migrations.AddField(
            model_name='address',
            name='record',
            field=models.ManyToManyField(blank=True, related_name='record_filter', through='geocode.RecordAddressIndex', to='geocode.Record'),
        ),
    ]
